### PR TITLE
Fix github auth attempt error while logged in

### LINKED ISSUE #53: Fix /login error
Fix `Cannot authenticate with Github` when navigating to /login route while logged in

### PR DESCRIPTION
**Pull request by thinktwice13**
- Was getting `Cannot authenticate with Github` when having a token and navigating to /login
- Get /login queryString from `props.location.search` instead of App.js route wrapper and remove unnecessary `withRouter`

Closes #53

### CODE REVIEW

File: src/components/Login/index.jsx [hunk 1]
```diff
@@ -25,15 +22,14 @@ class Login extends React.Component {
 
   async componentDidMount() {
     const { token, redirect } = localStorage
-    const { queryString, history } = this.props
-    const queryParams = new URLSearchParams(queryString);
+    const queryParams = new URLSearchParams(this.props.location.search);
     const code = queryParams.has('code') ? queryParams.get('code') : '';
```
Comment (the-vampiire) [inline src/components/Login/index.jsx]: this can be simplified. if the key is not in the URLSP object then it returns null

change to `const code = queryParams.get('code');`
